#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/christophe/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
numlockx &
dropboxd &
gnome-screensaver &
#xcompmgr -c &
volwheel &
conky &
emacs --daemon &
thunar --daemon &

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/christophe/.fluxbox/log"
